package com.rusefi.m749;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Build provenance generated by java-custom-ui/build.gradle into build.properties: board repository
 * and rusEFI submodule git hashes plus the build time. The same values are written to the jar
 * manifests so a stale rusefi_console.jar or install directory is recognizable from its first line.
 */
final class M749BuildInfo {
    static final String RESOURCE = "/com/rusefi/m749/build.properties";

    private M749BuildInfo() {
    }

    static String describe() {
        Properties properties = new Properties();
        try (InputStream in = M749BuildInfo.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                return "M749 build: unknown (build.properties resource missing; run the Gradle build)";
            }
            properties.load(in);
        } catch (IOException e) {
            return "M749 build: unknown (" + e.getMessage() + ")";
        }
        return describe(properties);
    }

    static String describe(Properties properties) {
        return "M749 build: board " + value(properties, "board.git")
                + ", rusefi " + value(properties, "rusefi.git")
                + ", built " + value(properties, "build.date");
    }

    private static String value(Properties properties, String key) {
        String value = properties.getProperty(key, "").trim();
        return value.isEmpty() ? "unknown" : value;
    }
}
